version: '3'
services:
   mydb:
     image: mysql:5.7.26
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: test
   mywordpress:
     depends_on:
       - mydb
     image: wordpress:latest
     ports:
       - 8080:80
     restart: always
